spring:
  application:
    name: integration-hubspot

server:
  port: 8081

hubspot:
  clientId: ${clientId}
  clientSecret: ${clientSecret}
  scopes: ${scopes}
  url: ${url-auth}
  redirectUri: ${redirect-url}

hub-api:
  base-url: ${url-hubapi}